CREATE TABLE IF NOT EXISTS notification_deliveries (
  delivery_id VARCHAR(64) PRIMARY KEY,
  event_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  occurred_at VARCHAR(40) NOT NULL,
  contract_id VARCHAR(255),
  run_id VARCHAR(64),
  base_version VARCHAR(255),
  candidate_version VARCHAR(255),
  commit_sha VARCHAR(255),
  triggered_by VARCHAR(255),
  policy_pack VARCHAR(255),
  summary LONGTEXT NOT NULL,
  breaking_changes LONGTEXT NOT NULL,
  warnings LONGTEXT NOT NULL,
  links LONGTEXT NOT NULL,
  dedupe_key VARCHAR(512) NOT NULL,
  sink_name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  created_at VARCHAR(40) NOT NULL,
  last_attempt_at VARCHAR(40),
  delivered_at VARCHAR(40),
  next_attempt_at VARCHAR(40),
  failure_message LONGTEXT,
  UNIQUE KEY idx_notification_deliveries_dedupe_sink (dedupe_key, sink_name),
  KEY idx_notification_deliveries_dispatch (status, next_attempt_at, created_at)
) ENGINE=InnoDB;
