CREATE TABLE IF NOT EXISTS check_evidence (
  evidence_id VARCHAR(64) PRIMARY KEY,
  idempotency_key VARCHAR(512) NOT NULL,
  payload_sha256 VARCHAR(64) NOT NULL,
  contract_id VARCHAR(255) NOT NULL,
  base_version VARCHAR(255) NOT NULL,
  candidate_version VARCHAR(255) NOT NULL,
  compatibility_mode VARCHAR(32) NOT NULL,
  commit_sha VARCHAR(255),
  base_schema_sha256 VARCHAR(64) NOT NULL,
  candidate_schema_sha256 VARCHAR(64) NOT NULL,
  engine_version VARCHAR(255) NOT NULL,
  engine_compatibility_protocol VARCHAR(64) NOT NULL,
  policy_pack_name VARCHAR(255) NOT NULL,
  policy_pack_sha256 VARCHAR(64) NOT NULL,
  local_status VARCHAR(16) NOT NULL,
  breaking_changes LONGTEXT NOT NULL,
  warnings LONGTEXT NOT NULL,
  executed_at VARCHAR(40) NOT NULL,
  ci_identity VARCHAR(512) NOT NULL,
  build_url VARCHAR(2048),
  raw_evidence LONGTEXT NOT NULL,
  authenticated_identity VARCHAR(512) NOT NULL,
  import_status VARCHAR(32) NOT NULL,
  verification_reason LONGTEXT,
  authoritative_run_id VARCHAR(64),
  imported_at VARCHAR(40) NOT NULL,
  UNIQUE KEY uq_check_evidence_idempotency (idempotency_key),
  KEY idx_check_evidence_contract_imported (contract_id, imported_at, evidence_id),
  KEY idx_check_evidence_status_imported (import_status, imported_at, evidence_id),
  CONSTRAINT fk_check_evidence_authoritative_run
    FOREIGN KEY (authoritative_run_id) REFERENCES check_runs(run_id)
) ENGINE=InnoDB;
