#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PROFILE="dcg-s3"
REGION="ap-south-1"
BUCKET=""
PREFIX="contracts"
SERVICE_URL="http://localhost:8080"
CONTRACT_ID="user.events"
ENV_FILE="/tmp/dcg-s3-demo.env"
FORCE_NO_PROMPT=0
APP_USER="${DCG_APP_USERNAME:-admin}"
APP_PASSWORD="${DCG_APP_PASSWORD:-change-me}"
PROFILE_EXPLICIT=0
REGION_EXPLICIT=0
PREFIX_EXPLICIT=0

usage() {
  cat <<'EOF'
Usage:
  s3-artifact-demo.sh <command> [options]

Commands:
  setup           Create/configure a demo bucket and upload sample raw data.
  seed-contract   Create contract v1 + v2 through local contract-service API.
  verify          Show S3 objects and query contract API.
  cleanup         Delete all versions/delete-markers and remove bucket.
  full            Run setup + seed-contract + verify.
  print-env       Print the current resolved configuration.

Options:
  --profile NAME        AWS CLI profile (default: dcg-s3)
  --region REGION       AWS region (default: ap-south-1)
  --bucket NAME         S3 bucket name (default: read from env file or auto-generate for setup)
  --prefix PREFIX       Artifact prefix (default: contracts)
  --service-url URL     API base URL (default: http://localhost:8080)
  --contract-id ID      Contract ID for seed calls (default: user.events)
  --env-file PATH       Env file path (default: /tmp/dcg-s3-demo.env)
  --username NAME       Contract-service basic-auth username (default: env DCG_APP_USERNAME or admin)
  --password VALUE      Contract-service basic-auth password (default: env DCG_APP_PASSWORD or change-me)
  --yes                 Skip cleanup confirmation prompt
  -h, --help            Show this help

Examples:
  scripts/aws/s3-artifact-demo.sh setup --profile dcg-s3
  scripts/aws/s3-artifact-demo.sh seed-contract --bucket my-bucket
  scripts/aws/s3-artifact-demo.sh verify --bucket my-bucket
  scripts/aws/s3-artifact-demo.sh cleanup --bucket my-bucket --yes
EOF
}

log() {
  printf '[dcg-s3-demo] %s\n' "$*"
}

die() {
  printf '[dcg-s3-demo] ERROR: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

aws_cli() {
  aws --profile "$PROFILE" --region "$REGION" "$@"
}

parse_args() {
  if [[ $# -lt 1 ]]; then
    usage
    exit 1
  fi

  if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    usage
    exit 0
  fi

  COMMAND="$1"
  shift

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --profile)
        [[ $# -ge 2 ]] || die "--profile requires a value"
        PROFILE="$2"
        PROFILE_EXPLICIT=1
        shift 2
        ;;
      --region)
        [[ $# -ge 2 ]] || die "--region requires a value"
        REGION="$2"
        REGION_EXPLICIT=1
        shift 2
        ;;
      --bucket)
        [[ $# -ge 2 ]] || die "--bucket requires a value"
        BUCKET="$2"
        shift 2
        ;;
      --prefix)
        [[ $# -ge 2 ]] || die "--prefix requires a value"
        PREFIX="$2"
        PREFIX_EXPLICIT=1
        shift 2
        ;;
      --service-url)
        [[ $# -ge 2 ]] || die "--service-url requires a value"
        SERVICE_URL="$2"
        shift 2
        ;;
      --contract-id)
        [[ $# -ge 2 ]] || die "--contract-id requires a value"
        CONTRACT_ID="$2"
        shift 2
        ;;
      --env-file)
        [[ $# -ge 2 ]] || die "--env-file requires a value"
        ENV_FILE="$2"
        shift 2
        ;;
      --username)
        [[ $# -ge 2 ]] || die "--username requires a value"
        APP_USER="$2"
        shift 2
        ;;
      --password)
        [[ $# -ge 2 ]] || die "--password requires a value"
        APP_PASSWORD="$2"
        shift 2
        ;;
      --yes)
        FORCE_NO_PROMPT=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "Unknown argument: $1"
        ;;
    esac
  done
}

load_saved_env() {
  if [[ -f "$ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    if [[ -z "$BUCKET" && -n "${DCG_S3_BUCKET:-}" ]]; then
      BUCKET="$DCG_S3_BUCKET"
    fi
    if [[ "$PREFIX_EXPLICIT" -eq 0 && -n "${DCG_S3_PREFIX:-}" ]]; then
      PREFIX="$DCG_S3_PREFIX"
    fi
    if [[ "$REGION_EXPLICIT" -eq 0 && -n "${AWS_REGION:-}" ]]; then
      REGION="$AWS_REGION"
    fi
    if [[ "$PROFILE_EXPLICIT" -eq 0 && -n "${AWS_PROFILE:-}" ]]; then
      PROFILE="$AWS_PROFILE"
    fi
    if [[ -n "${DCG_SERVICE_URL:-}" ]]; then
      SERVICE_URL="$DCG_SERVICE_URL"
    fi
    if [[ -n "${DCG_CONTRACT_ID:-}" ]]; then
      CONTRACT_ID="$DCG_CONTRACT_ID"
    fi
    if [[ -n "${DCG_APP_PASSWORD:-}" ]]; then
      APP_PASSWORD="$DCG_APP_PASSWORD"
    fi
  fi
}

ensure_bucket_for_non_setup() {
  load_saved_env
  [[ -n "$BUCKET" ]] || die "Bucket is required. Pass --bucket or run setup first."
}

write_env_file() {
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/aws/s3-artifact-demo.sh
export AWS_PROFILE="$PROFILE"
export AWS_REGION="$REGION"
export DCG_S3_BUCKET="$BUCKET"
export DCG_S3_PREFIX="$PREFIX"
export DCG_SERVICE_URL="$SERVICE_URL"
export DCG_CONTRACT_ID="$CONTRACT_ID"
EOF
  log "Saved env file: $ENV_FILE"
}

generate_bucket_name() {
  local account_id timestamp
  account_id="$(aws_cli sts get-caller-identity --query Account --output text)"
  timestamp="$(date +%Y%m%d%H%M%S)"
  BUCKET="dcg-artifacts-${account_id}-${timestamp}"
}

bucket_exists() {
  aws_cli s3api head-bucket --bucket "$BUCKET" >/dev/null 2>&1
}

create_bucket_if_needed() {
  if bucket_exists; then
    log "Using existing bucket: $BUCKET"
    return
  fi

  if [[ "$REGION" == "us-east-1" ]]; then
    aws_cli s3api create-bucket \
      --bucket "$BUCKET" >/dev/null
  else
    aws_cli s3api create-bucket \
      --bucket "$BUCKET" \
      --create-bucket-configuration "LocationConstraint=$REGION" >/dev/null
  fi
  log "Created bucket: $BUCKET"
}

configure_bucket() {
  aws_cli s3api put-public-access-block \
    --bucket "$BUCKET" \
    --public-access-block-configuration \
      BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true

  aws_cli s3api put-bucket-ownership-controls \
    --bucket "$BUCKET" \
    --ownership-controls \
      "Rules=[{ObjectOwnership=BucketOwnerEnforced}]"

  aws_cli s3api put-bucket-encryption \
    --bucket "$BUCKET" \
    --server-side-encryption-configuration \
      "Rules=[{ApplyServerSideEncryptionByDefault={SSEAlgorithm=AES256}}]"

  aws_cli s3api put-bucket-versioning \
    --bucket "$BUCKET" \
    --versioning-configuration Status=Enabled

  log "Enabled Block Public Access, bucket-owner-enforced ownership, SSE-S3, and versioning"
}

seed_raw_sample() {
  local sample_file
  sample_file="$(mktemp "${TMPDIR:-/tmp}/dcg-events-XXXX.json")"

  cat > "$sample_file" <<'JSON'
{"user_id":"u_1001","event_type":"click","timestamp":"2026-05-13T12:00:00Z","page":"/home","session_id":"s_9001","metadata":{"device":"mobile","country":"IN"}}
{"user_id":"u_1002","event_type":"view","timestamp":"2026-05-13T12:00:08Z","page":"/pricing","session_id":"s_9002","metadata":{"device":"desktop","country":"IN"}}
JSON

  aws_cli s3api put-object --bucket "$BUCKET" --key "raw/user-events/year=2026/month=05/.keep" >/dev/null
  aws_cli s3api put-object --bucket "$BUCKET" --key "$PREFIX/.keep" >/dev/null
  aws_cli s3 cp "$sample_file" "s3://$BUCKET/raw/user-events/year=2026/month=05/events_001.json" >/dev/null
  rm -f "$sample_file"

  log "Uploaded sample raw data to s3://$BUCKET/raw/user-events/year=2026/month=05/"
}

print_service_run_hint() {
  cat <<EOF

Start contract-service with S3 backend:
  cd "$ROOT_DIR"
  CONTRACTS_ROOT="/tmp/dcg-contracts-cache" \\
  CONTRACTS_ARTIFACT_BACKEND=s3 \\
  CONTRACTS_ARTIFACT_S3_BUCKET="$BUCKET" \\
  CONTRACTS_ARTIFACT_S3_REGION="$REGION" \\
  CONTRACTS_ARTIFACT_S3_PREFIX="$PREFIX" \\
  CONTRACTS_ARTIFACT_S3_FALLBACK_ENABLED=false \\
  CONTRACTS_ARTIFACT_S3_LOCAL_CACHE_ROOT="/tmp/dcg-contracts-cache" \\
  CONTRACTS_ARTIFACT_S3_SERVER_SIDE_ENCRYPTION=AES256 \\
  APP_SECURITY_ENABLED=true \\
  DCG_APP_USERNAME="$APP_USER" \\
  docker compose --env-file .env -f docker-compose.yml up --build -d

Credential note:
  Contract-service basic auth uses DCG_APP_USERNAME / DCG_APP_PASSWORD from .env.
  The container must receive AWS credentials through env vars, IAM role, or app-scoped
  CONTRACTS_ARTIFACT_S3_ACCESS_KEY / CONTRACTS_ARTIFACT_S3_SECRET_KEY. Do not commit them.
EOF
}

curl_auth_args() {
  printf '%s:%s' "$APP_USER" "$APP_PASSWORD"
}

http_post_json() {
  local url="$1"
  local payload="$2"
  local body_file status_code
  body_file="$(mktemp "${TMPDIR:-/tmp}/dcg-http-XXXX.json")"

  set +e
  status_code="$(curl -sS -o "$body_file" -w "%{http_code}" \
    -u "$(curl_auth_args)" \
    -X POST "$url" \
    -H "Content-Type: application/json" \
    -d "$payload")"
  local curl_exit=$?
  set -e

  local body
  body="$(cat "$body_file")"
  rm -f "$body_file"

  if [[ $curl_exit -ne 0 ]]; then
    die "HTTP request failed for $url"
  fi

  printf '%s\n' "$status_code"
  printf '%s\n' "$body"
}

ensure_service_up() {
  if ! curl -fsS "$SERVICE_URL/actuator/health" >/dev/null 2>&1; then
    die "Service is not reachable at $SERVICE_URL. Start contract-service first."
  fi
}

setup() {
  require_cmd aws
  [[ -n "$BUCKET" ]] || generate_bucket_name
  create_bucket_if_needed
  configure_bucket
  seed_raw_sample
  write_env_file
  print_service_run_hint
}

seed_contract() {
  require_cmd curl
  require_cmd aws
  ensure_bucket_for_non_setup
  ensure_service_up

  log "Seeding contract $CONTRACT_ID (v1 then v2)"

  local create_response create_status create_body
  create_response="$(http_post_json "$SERVICE_URL/contracts" "{
  \"contractId\": \"$CONTRACT_ID\",
  \"ownerTeam\": \"platform\",
  \"domain\": \"analytics\",
  \"compatibilityMode\": \"BACKWARD\",
  \"policyPack\": \"baseline\",
  \"initialVersion\": \"v1\",
  \"schema\": {
    \"type\": \"object\",
    \"properties\": {
      \"user_id\": {\"type\":\"string\"},
      \"event_type\": {\"type\":\"string\"},
      \"timestamp\": {\"type\":\"string\"},
      \"page\": {\"type\":\"string\"},
      \"session_id\": {\"type\":\"string\"},
      \"metadata\": {\"type\":\"object\"}
    }
  }
}")"

  create_status="${create_response%%$'\n'*}"
  create_body="${create_response#*$'\n'}"
  printf 'create-contract status=%s\n%s\n' "$create_status" "$create_body"
  if [[ "$create_status" != "201" && "$create_status" != "409" ]]; then
    die "Contract create failed with HTTP $create_status"
  fi

  local version_response version_status version_body
  version_response="$(http_post_json "$SERVICE_URL/contracts/$CONTRACT_ID/versions" "{
  \"version\": \"v2\",
  \"schema\": {
    \"type\": \"object\",
    \"properties\": {
      \"user_id\": {\"type\":\"string\"},
      \"event_type\": {\"type\":\"string\"},
      \"timestamp\": {\"type\":\"string\"},
      \"page\": {\"type\":\"string\"},
      \"session_id\": {\"type\":\"string\"},
      \"metadata\": {\"type\":\"object\"},
      \"app_version\": {\"type\":\"string\"}
    }
  }
}")"

  version_status="${version_response%%$'\n'*}"
  version_body="${version_response#*$'\n'}"
  printf 'create-version status=%s\n%s\n' "$version_status" "$version_body"
  if [[ "$version_status" != "201" ]]; then
    if [[ "$version_status" == "400" && ( "$version_body" == *"Version already exists"* || "$version_body" == *"New version must be greater than existing latest version v2."* ) ]]; then
      log "Version v2 already exists; continuing"
    else
      die "Contract version create failed with HTTP $version_status"
    fi
  fi
}

verify() {
  require_cmd aws
  require_cmd curl
  ensure_bucket_for_non_setup

  log "Listing S3 objects in s3://$BUCKET/"
  aws_cli s3 ls "s3://$BUCKET/" --recursive

  if curl -fsS "$SERVICE_URL/actuator/health" >/dev/null 2>&1; then
    log "Service is up; fetching contract detail"
    curl -sS -u "$(curl_auth_args)" "$SERVICE_URL/contracts/$CONTRACT_ID"
    printf '\n'
  else
    log "Service not running at $SERVICE_URL; skipping API verify"
  fi
}

delete_batch() {
  local query_root="$1"
  local count batch_json
  count="$(aws_cli s3api list-object-versions \
    --bucket "$BUCKET" \
    --query "length(${query_root} || \`[]\`)" \
    --output text)"

  if [[ "$count" == "None" || "$count" == "0" ]]; then
    return 1
  fi

  batch_json="$(aws_cli s3api list-object-versions \
    --bucket "$BUCKET" \
    --query "{Objects: ${query_root}[].{Key:Key,VersionId:VersionId}}" \
    --output json)"

  aws_cli s3api delete-objects \
    --bucket "$BUCKET" \
    --delete "$batch_json" >/dev/null
  return 0
}

cleanup() {
  require_cmd aws
  ensure_bucket_for_non_setup

  if [[ "$FORCE_NO_PROMPT" -ne 1 ]]; then
    printf 'Delete bucket "%s" and all versions? Type YES to continue: ' "$BUCKET"
    read -r answer
    [[ "$answer" == "YES" ]] || die "Cleanup cancelled"
  fi

  if ! bucket_exists; then
    log "Bucket not found or inaccessible: $BUCKET"
    return
  fi

  log "Deleting all object versions and delete markers"
  while true; do
    local_any=0
    if delete_batch "Versions"; then
      local_any=1
      log "Deleted one batch of versions"
    fi
    if delete_batch "DeleteMarkers"; then
      local_any=1
      log "Deleted one batch of delete markers"
    fi
    if [[ "$local_any" -eq 0 ]]; then
      break
    fi
  done

  aws_cli s3api delete-bucket \
    --bucket "$BUCKET"
  log "Deleted bucket: $BUCKET"
}

print_env() {
  load_saved_env
  cat <<EOF
PROFILE=$PROFILE
REGION=$REGION
BUCKET=$BUCKET
PREFIX=$PREFIX
SERVICE_URL=$SERVICE_URL
CONTRACT_ID=$CONTRACT_ID
ENV_FILE=$ENV_FILE
ROOT_DIR=$ROOT_DIR
APP_USER=$APP_USER
EOF
}

main() {
  parse_args "$@"

  case "$COMMAND" in
    setup)
      setup
      ;;
    seed-contract)
      seed_contract
      ;;
    verify)
      verify
      ;;
    cleanup)
      cleanup
      ;;
    full)
      setup
      seed_contract
      verify
      ;;
    print-env)
      print_env
      ;;
    *)
      usage
      die "Unknown command: $COMMAND"
      ;;
  esac
}

main "$@"
