package com.ideas.contracts.service;

public enum NotificationEventType {
  CONTRACT_CHECK_FAILED,
  CONTRACT_VERSION_REJECTED,
  CONTRACT_REGISTERED,
  SCHEMA_VERSION_PUBLISHED,
  POLICY_PACK_RESOLUTION_FAILED,
  POLICY_PACK_CONFIG_INVALID,
  NOTIFICATION_DELIVERY_FAILED
}
